name: Ubuntu Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: apt install
      run: sudo apt install -y build-essential cmake libgl1-mesa-dev qt6-tools-dev qt6-base-dev qt6-base-dev-tools qt6-declarative-dev libqt6widgets6 libqt6quickwidgets6 libqt6gui6 qt6-l10n-tools
    - name: cmake 
      run: cmake -B build
    - name: make
      run: make -C build -j8 all
