name: Windows Build

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
        version: ['6.6.0']
    steps:
    - uses: actions/checkout@v1

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ matrix.version }}
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        modules: 'qtwebengine qtlocation qtpositioning'
        tools: 'tools_openssl_x64,qt.tools.openssl.win_x64'


    - name: Build
      if: startsWith(matrix.os, 'windows')
      run: |
        call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        mkdir build
        cd build
        cmake -DCMAKE_PREFIX_PATH="C:\Qt\6.6.0\msvc2019_64" -DCMAKE_GENERATOR_PLATFORM=x64 -DCMAKE_BUILD_TYPE=RELEASE -DDEPLOY_QT_LIBRARIES=ON -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON ..
        if %errorlevel% neq 0 exit /b %errorlevel%
        cmake --build . --config Release
        if %errorlevel% neq 0 exit /b %errorlevel%
        ctest -C Release .
        if %errorlevel% neq 0 exit /b %errorlevel%
        cp *.qm ./Release
        for /R c:\Qt\Tools\OpenSSL %%f in (*.dll) do copy %%f "%CD%\Release"
      shell: cmd


    - name: Archive build results
      uses: actions/upload-artifact@v2
      with:
        name: mvc-demo
        path: ./build/Release/*
